deployment.javaws.jre.0.registered=true
deployment.javaws.jre.0.args=
deployment.javaws.jre.0.enabled=true
deployment.javaws.jre.0.location=http\://java.sun.com/products/autodl/j2se
deployment.javaws.jre.0.osarch=x86
deployment.javaws.jre.0.product=1.6.0_32
deployment.javaws.jre.0.path=C\:\\Program Files (x86)\\Java\\jre6\\bin\\javaw.exe
deployment.javaws.jre.0.osname=Windows
deployment.javaws.jre.0.platform=1.6
deployment.browser.path=C\:\\Program Files\\Mozilla Firefox\\firefox.exe
deployment.capture.mime.types=true
deployment.version=6.0
